### ISSUE TITLE
Test for adaptive modeler disabled

### ISSUE THREAD

**Issue by marcusritter1** [extra-p/extrap#22]
I will disable the test for the adaptive modeler in the new release for now. This has the following reasons:

- Test takes 7 min. to pass, see the output below. The reason for this is the tensorflow initialization and model training.
- Need to install the extrap-adaptive-modeler package (https://github.com/extra-p/extrap-adaptive-modeler) for the test to work, otherwise the modeler code does not work.
- The test does pass though

================= 4 passed, 99 warnings in 436.73s (0:07:16) ==================

**Comment by ageiss2** [comment]
Test for adaptive modeler is now optional (see 272d5c8e58abb68ffc488d2b100728149a80dc43). It will be run if the extrap-adaptive-modeler package is installed.
