### ISSUE TITLE
GUI crashes when using model other than `Model mean`

### ISSUE THREAD

**Issue by martinclemens** [extra-p/extrap#27]
Trying to generate models in the GUI using `Model Median/Minimum/Maximum` instead of `Model mean` crashes with the following traceback
```
Traceback (most recent call last):
  File "/home/clem_mr/installs/extrap/venv/lib/python3.8/site-packages/extrap/gui/ModelerWidget.py", line 136, in remodel
    elif self.model_median_radio.isChecked():
AttributeError: 'ModelerWidget' object has no attribute 'model_median_radio'
```
and it seems like `self.model_median_radio` is commented out in line 59.
Used version the current release 4.2.0

**Comment by ageiss2** [comment]
Thank you for reporting this bug, we have fixed in 60d76e1 and released an updated version of Extra-P.
