### ISSUE TITLE
support Docker environment

### ISSUE THREAD

**Issue by arima0714** [extra-p/extrap#4]
I could set up Extra-P on CLI but I could not execute `extrap-gui` on macOS and WSL2.

I suppose that Extra-P needs executable doker container environment then many users will use Extra-P more easily.

I'm trying to use `extrap-gui` with docker container. I will send Pull Request when finished to building container envrionment.

**Comment by arima0714** [comment]
I made Pull request #5 for this Issue.

**Comment by MeaParvitas** [comment]
Extra-P should support Windows and macOS by default. So the extrap-gui should be executable. Could you please specify which system you are using and which version? I will take a look at the issue then. I will think about adding docker support for the next release.

**Comment by MeaParvitas** [comment]
Extra-P is currently supported by docker and it is very simple to deploy it using a docker container. Therefore, we do not see any benefit in providing a specific docker container specifically for Extra-P or certain use cases. Consequently, I will close the issue.
