### ISSUE TITLE
Feedback aiXcelerate Aachen 2022

### ISSUE THREAD

**Issue by marcusritter1** [extra-p/extrap#6]
## Feedback:

- search function for callpaths in selection view to filter the callpaths
- gui does not work/start on newer MacOS versions
- some gui functions including weak/strong scaling selection, all right click menus, do not work when using x-/port forwarding when running extrap-gui on the cluster
- measurement points plot is showing data incorrectly when using only one parameter (not very intuitive for users that don't know about it)
- weak/strong scaling selection missing for other input methods than Cube files... would be easier for the user if extra-p automatically multiplies the number of processes with the measured metric than doing it manually...

**Comment by ageiss2** [comment]
Gui does not work/start on newer MacOS versions is adressed in 5bce7e9

**Comment by MeaParvitas** [comment]
Ignore: 

* some gui functions including weak/strong scaling selection, all right click menus, do not work when using x-/port forwarding when running extrap-gui on the cluster

Tool is not intended to be used like that.
